import type { FaqItem } from "./types";

export const faqCategories = ["All", "Visits", "Coverage", "Results", "Prescriptions", "Clinic", "Privacy", "Pain Centre", "Infusion", "Aesthetics", "Rehab"];

export const faqItems: FaqItem[] = [
  {
    category: "Visits",
    q: "Will a student be involved in my care?",
    a: "Sometimes. We are a teaching clinic with Toronto Metropolitan University and Anderson College. A learner may join your visit under direct supervision of a licensed clinician. We tell you beforehand, and you can ask for the clinician only at any time.",
    linkLabel: "About our teaching clinic",
    linkPage: "about",
  },
  {
    category: "Visits",
    q: "Who supervises learners?",
    a: "Physician learners are supervised by Dr. Johnny Nguyen, Medical Director. Laboratory learners are supervised by our Lab Manager. Learners never assess, treat or draw blood unsupervised.",
    linkLabel: "Standards of care",
    linkPage: "standards",
  },
  {
    category: "Visits",
    q: "Are you accepting new patients?",
    a: "Yes, for Family Medicine at Thornhill. Register online and we confirm within two business days. Pain Centre, Rehab, Infusion and Aesthetics do not need you to be a rostered patient.",
    linkLabel: "Register as a new patient",
    linkPage: "register",
  },
  {
    category: "Visits",
    q: "Do I need a referral?",
    a: "Not for Family Medicine, Rehab, Infusion Therapy or Aesthetics. The Pain Centre needs a physician referral for OHIP-covered care; if you have no family doctor, a family medicine assessment here can lead to an internal referral.",
    linkLabel: "Refer a patient",
    linkPage: "referrals",
  },
  {
    category: "Visits",
    q: "How do I book?",
    a: "Online in three steps, or call 905-709-3222 during clinic hours. Online requests are confirmed by our team the same day.",
    linkLabel: "Book a visit",
    linkPage: "book",
  },
  {
    category: "Visits",
    q: "What should I bring to a first visit?",
    a: "Your Ontario health card, a list of medications, and any recent results or imaging. Arrive ten minutes early for a new patient visit.",
  },
  {
    category: "Visits",
    q: "Can I see the same doctor each time?",
    a: "Yes. Rostered family medicine patients are matched to one physician. If they are away, the other physician covers with the same chart.",
  },
  {
    category: "Visits",
    q: "Do you offer phone or video visits?",
    a: "Yes, for follow-ups, results and renewals with existing patients. New concerns are usually seen in person first.",
  },
  {
    category: "Coverage",
    q: "What is covered by OHIP?",
    a: "Family medicine visits, Pain Centre assessments and physician-ordered bloodwork are insured. Wellness infusions, aesthetic treatments and most third-party forms are not.",
    linkLabel: "Patient rights and costs",
    linkPage: "rights",
  },
  {
    category: "Coverage",
    q: "What if I do not have OHIP?",
    a: "We see uninsured patients at posted rates, told to you before the visit. A receipt is provided for private insurance or reimbursement.",
  },
  {
    category: "Coverage",
    q: "Is rehab covered?",
    a: "Physiotherapy, chiropractic and massage are billed to extended health plans, MVA insurers or WSIB where applicable. We can direct-bill many plans. Self-pay rates are posted at the desk.",
    linkLabel: "Rehab and Recovery",
    linkPage: "rehab",
  },
  {
    category: "Coverage",
    q: "Do you charge for forms and notes?",
    a: "Forms for medical care are covered. Third-party forms such as camp, daycare, employer and insurance carry a small uninsured fee, told to you in advance with a receipt.",
  },
  {
    category: "Results",
    q: "How do I get my results?",
    a: "Your doctor reviews everything first. Normal results are shared at your follow-up or through the portal; anything urgent is phoned the same day.",
  },
  {
    category: "Results",
    q: "How long does bloodwork take?",
    a: "About a week for most tests. Ferritin and hemoglobin before an iron infusion are back in two to three days.",
    linkLabel: "Bloodwork on site",
    linkPage: "blood",
  },
  {
    category: "Results",
    q: "Can I get a copy of my records?",
    a: "Yes. Submit a written request at the desk or by email. Copies for your own use are provided within 30 days; a transfer fee may apply for full chart copies.",
    linkLabel: "Privacy policy",
    linkPage: "privacy",
  },
  {
    category: "Prescriptions",
    q: "How do I renew a prescription?",
    a: "Existing patients can request a renewal by phone or portal. Allow two business days. Some medications need a visit before renewal.",
  },
  {
    category: "Prescriptions",
    q: "Can you send prescriptions to any pharmacy?",
    a: "Yes. Tell us the pharmacy at the visit and we fax or send electronically. Vietnamese-speaking pharmacies nearby are listed at the desk.",
  },
  {
    category: "Clinic",
    q: "Where do I park?",
    a: "Free on-site parking at 700 Centre St, inside the Walmart plaza. Accessible spaces are close to the entrance.",
    linkLabel: "Our clinics",
    linkPage: "locations",
  },
  {
    category: "Clinic",
    q: "What are your hours?",
    a: "Mon, Wed, Thu 9am to 4pm; Tue 3pm to 9pm; Sat 8am to 4pm; Sun 8am to 2pm. Closed Fridays and statutory holidays. The bar at the top of the site shows whether we are open right now.",
    linkLabel: "Hours and directions",
    linkPage: "locations",
  },
  {
    category: "Clinic",
    q: "Is the clinic accessible?",
    a: "Yes. Level entry, wide hallways, accessible washrooms and treatment rooms. Service animals and support persons are welcome.",
    linkLabel: "Accessibility statement",
    linkPage: "accessibility",
  },
  {
    category: "Clinic",
    q: "When does Maple open?",
    a: "Maple at 2620 Rutherford Rd is opening soon. Pre-registration is open now so you can be matched before day one.",
    linkLabel: "Join the Maple list",
    linkPage: "locations",
  },
  {
    category: "Clinic",
    q: "Do you speak Vietnamese?",
    a: "Yes. Both physicians and several staff speak Vietnamese. The site is available in Tiếng Việt using the switch at the top.",
  },
  {
    category: "Privacy",
    q: "Who can see my health information?",
    a: "Only the clinicians and staff involved in your care. We never confirm whether someone is a patient to anyone else without your consent.",
    linkLabel: "Privacy policy",
    linkPage: "privacy",
  },
  {
    category: "Privacy",
    q: "Can my teenager have a private visit?",
    a: "Yes. Teens may book and attend alone. Part of every teen visit is private, within the limits of the law.",
    linkLabel: "Children and youth",
    linkPage: "kids",
  },
  {
    category: "Privacy",
    q: "Will you text or email me?",
    a: "Appointment reminders go to the number or email you give us. Promotional messages are sent only if you opt in, and every one has an unsubscribe.",
  },
  {
    category: "Visits",
    q: "What is your late and cancellation policy?",
    a: "Give us 24 hours notice to cancel or move a visit so the time can go to someone else. Arriving more than 15 minutes late may mean rebooking. Missed uninsured visits may carry a fee.",
  },
  {
    category: "Visits",
    q: "Can I bring my children to my own appointment?",
    a: "Yes. There is space in the waiting area, and if a child needs to be seen too, book them back to back with you.",
  },
  {
    category: "Visits",
    q: "Can I bring someone with me?",
    a: "Yes. A family member, friend or support person is welcome in the room at any visit.",
  },
  {
    category: "Visits",
    q: "Do you have interpreters?",
    a: "Vietnamese is spoken in clinic. For other languages, tell us when booking and we arrange a phone interpreter at no cost to you.",
  },
  {
    category: "Pain Centre",
    q: "What happens at a first Pain Centre visit?",
    a: "A 20 minute assessment: your history, an examination, a review of imaging and what has been tried. You leave with a plan, which may include injections, medication changes, rehab or a combination.",
    linkLabel: "Pain Centre",
    linkPage: "pain",
  },
  {
    category: "Pain Centre",
    q: "Is the Pain Centre covered by OHIP?",
    a: "Assessments and most physician-delivered injections are insured. Some medications and devices are not; we tell you before anything is ordered.",
  },
  {
    category: "Pain Centre",
    q: "Do you do nerve blocks and joint injections?",
    a: "Yes, in clinic, usually at a follow-up after the assessment. Most take under 20 minutes and you can drive home unless sedation is used.",
    linkLabel: "Where does it hurt?",
    linkPage: "pain",
  },
  {
    category: "Pain Centre",
    q: "How long is the wait?",
    a: "New assessments are usually within two to three weeks of referral. Urgent cases flagged by your doctor are seen sooner.",
    linkLabel: "Refer a patient",
    linkPage: "referrals",
  },
  {
    category: "Infusion",
    q: "How long does an infusion take?",
    a: "Wellness drips 45 to 60 minutes; iron infusions about an hour plus a 30 minute observation. Injections take a few minutes.",
    linkLabel: "Infusion Therapy",
    linkPage: "infusion",
  },
  {
    category: "Infusion",
    q: "Who should not have an iron infusion?",
    a: "Anyone without confirmed iron deficiency on bloodwork, with certain infections or liver conditions, or with a past reaction to IV iron. The physician screens every patient first.",
    linkLabel: "Iron therapy",
    linkPage: "infusion",
  },
  {
    category: "Infusion",
    q: "Are drips covered by OHIP?",
    a: "No. Wellness infusions and injections are self-pay, priced with HST on the menu. Iron infusion for confirmed deficiency is a physician visit; the iron product itself may be covered by your drug plan.",
    linkLabel: "Pricing",
    linkPage: "infusion",
  },
  {
    category: "Infusion",
    q: "Do I need a consult before a drip?",
    a: "A short nurse screening the first time, and a physician review for iron or anything prescription-based. After that, book straight in.",
  },
  {
    category: "Aesthetics",
    q: "Do I need a consultation first?",
    a: "Yes, for anything injectable or device-based. A 30 minute consult covers goals, options, cost and what to expect. Some treatments can follow at the same visit.",
    linkLabel: "Medical Aesthetics",
    linkPage: "aesthetics",
  },
  {
    category: "Aesthetics",
    q: "Is there downtime?",
    a: "It depends on the treatment. Most injectables have little to none; some skin treatments need a few days of redness. We tell you before booking so you can plan around it.",
  },
  {
    category: "Aesthetics",
    q: "How is pricing set?",
    a: "Per treatment or per unit, listed with HST, and confirmed at the consult before anything is done. Packages are optional, never required.",
  },
  {
    category: "Aesthetics",
    q: "Who performs treatments?",
    a: "Physicians and aesthetic nurses working under physician direction. You are told who is treating you and can ask for a specific clinician.",
  },
  {
    category: "Rehab",
    q: "Which insurance plans do you direct-bill?",
    a: "Most major extended health plans. Bring your card and we check at the desk. If we cannot direct-bill, you receive a receipt to submit yourself.",
    linkLabel: "Rehab and Recovery",
    linkPage: "rehab",
  },
  {
    category: "Rehab",
    q: "Do you handle MVA and WSIB claims?",
    a: "Yes. Bring your claim number. We complete the required treatment plans and forms and bill the insurer directly.",
  },
  {
    category: "Rehab",
    q: "Do I need a doctor’s note for physio, chiro or massage?",
    a: "Not to be seen. Some insurance plans require one for reimbursement, so check yours; our physicians can provide it if you are a patient.",
  },
  {
    category: "Rehab",
    q: "How many visits will I need?",
    a: "Set after the first assessment and revisited as you progress. Nobody is booked into a package they do not need.",
  },
  {
    category: "Results",
    q: "Can I book online without calling?",
    a: "Yes. The Book a visit form takes a couple of minutes and is confirmed by our team the same day. Existing patients can also request through the portal.",
    linkLabel: "Book a visit",
    linkPage: "book",
  },
];
