import type { Job } from "./types";

/** Open roles (CMS collection). Order matches the prototype's ALL list. */
export const jobs: Job[] = [
  {
    id: "rn-infusion",
    title: "Registered Nurse, Infusion Therapy",
    location: "Thornhill",
    division: "Infusion Therapy",
    type: "Part time",
    schedule: "Tue, Sat, Sun",
    postedDate: "2026-09-12",
    summary: "IV starts, drip administration and patient monitoring in a lounge setting.",
    tint: "#E6F4EA",
    featured: true,
    requirements: ["CNO registration in good standing", "IV therapy certification", "One year of acute or infusion experience"],
  },
  {
    id: "pt",
    title: "Registered Physiotherapist",
    location: "Thornhill and Maple",
    division: "Rehab and Recovery",
    type: "Full time",
    schedule: "Weekdays, one evening",
    postedDate: "2026-09-08",
    summary: "Assessment and treatment across post-injury, MVA and chronic pain cases, coordinated with our pain physician.",
    tint: "#FFF3C4",
    featured: true,
    requirements: ["College of Physiotherapists of Ontario registration", "MVA and WSIB documentation experience an asset"],
  },
  {
    id: "moa-maple",
    title: "Medical Office Administrator",
    location: "Maple",
    division: "Front desk",
    type: "Full time",
    schedule: "Rotating, includes Saturdays",
    postedDate: "2026-09-01",
    summary: "Front desk, booking, OHIP billing and patient coordination for the Maple opening.",
    tint: "#EEF5FC",
    featured: true,
    requirements: ["MOA diploma or two years in a clinic", "OHIP billing", "Vietnamese is an asset"],
  },
  {
    id: "fp-maple",
    title: "Family Physician",
    location: "Maple",
    division: "Family Medicine",
    type: "Full or part time",
    schedule: "Flexible",
    postedDate: "2026-08-25",
    summary: "Join Dr. Nguyen and Dr. Truong with an established roster, shared chart and Pain Centre, Rehab and Infusion down the hall.",
    tint: "#FDE8E4",
    featured: true,
    requirements: ["CPSO independent practice licence", "CCFP or equivalent"],
  },
  {
    id: "rmt",
    title: "Registered Massage Therapist",
    location: "Thornhill",
    division: "Rehab and Recovery",
    type: "Contract",
    schedule: "Evenings and weekends",
    postedDate: "2026-09-15",
    summary: "Treatment within a multidisciplinary plan alongside physio and chiro.",
    tint: "#FFF3C4",
    featured: false,
    requirements: ["CMTO registration", "Insurance billing experience"],
  },
  {
    id: "aes-rn",
    title: "Aesthetic Nurse Injector",
    location: "Thornhill",
    division: "Medical Aesthetics",
    type: "Part time",
    schedule: "Thu to Sat",
    postedDate: "2026-09-10",
    summary: "Physician-directed neuromodulator and filler treatments with conservative planning.",
    tint: "#F3ECF7",
    featured: false,
    requirements: ["CNO registration", "Two years injecting experience", "Medical directive familiarity"],
  },
  {
    id: "mlt",
    title: "Medical Laboratory Technician, Phlebotomy",
    location: "Thornhill",
    division: "Family Medicine",
    type: "Part time",
    schedule: "Weekday mornings",
    postedDate: "2026-09-05",
    summary: "On-site blood draws, 10-lead ECG and specimen handling for the lab pickup.",
    tint: "#EEF5FC",
    featured: false,
    requirements: ["MLT or MLA/T certification", "ECG experience an asset"],
  },
  {
    id: "kin",
    title: "Kinesiologist",
    location: "Maple",
    division: "Rehab and Recovery",
    type: "Full time",
    schedule: "Weekdays",
    postedDate: "2026-08-30",
    summary: "Active rehab programming and return-to-work planning for the Maple opening.",
    tint: "#FFF3C4",
    featured: false,
    requirements: ["College of Kinesiologists of Ontario registration"],
  },
  {
    id: "chiro",
    title: "Chiropractor",
    location: "Maple",
    division: "Rehab and Recovery",
    type: "Contract",
    schedule: "Flexible",
    postedDate: "2026-08-28",
    summary: "Spine and joint care coordinated with the Pain Centre.",
    tint: "#FFF3C4",
    featured: false,
    requirements: ["CCO registration"],
  },
  {
    id: "mgr",
    title: "Clinic Manager",
    location: "Thornhill and Maple",
    division: "Operations",
    type: "Full time",
    schedule: "Weekdays",
    postedDate: "2026-09-14",
    summary: "Day-to-day operations across both sites, staffing, supplies and patient experience.",
    tint: "#EEF5FC",
    featured: false,
    requirements: ["Five years in healthcare operations", "Two years leading a team"],
  },
];

/** Filter chip values on the job board, in display order. */
export const jobFilters = {
  locations: ["All", "Thornhill", "Maple"],
  divisions: ["All", "Family Medicine", "Pain Centre", "Medical Aesthetics", "Infusion Therapy", "Rehab and Recovery", "Front desk", "Operations"],
  types: ["All", "Full time", "Part time", "Contract", "Full or part time"],
  sorts: ["Newest", "A to Z"],
} as const;

export type JobSort = (typeof jobFilters.sorts)[number];

/** "Today", "1 day ago", "N days ago", "1 week ago", "N weeks ago". */
export function postedAgo(posted: string, today: Date = new Date()): string {
  const d = Math.round((today.getTime() - new Date(posted).getTime()) / 864e5);
  return d <= 0 ? "Today" : d === 1 ? "1 day ago" : d < 7 ? d + " days ago" : d < 14 ? "1 week ago" : Math.round(d / 7) + " weeks ago";
}
