import React from 'react';
export function Chooser({ eyebrow, title, intro, options, results, tone = 'family', value, onChange, cta, style }) {
  const [inner, setInner] = React.useState(0); const pick = value ?? inner; const set = i => { setInner(i); onChange && onChange(i); };
  const r = results[pick] || results[0];
  return React.createElement('div', { style: { borderRadius: 28, background: 'var(--div-' + tone + ')', padding: '48px 40px', display: 'grid', gridTemplateColumns: '1fr 1.25fr', gap: 40, alignItems: 'start', color: 'var(--text-primary)', fontFamily: 'var(--font-ui)', ...style } },
    React.createElement('div', { style: { display: 'flex', flexDirection: 'column', gap: 18 } }, eyebrow ? React.createElement('span', { style: { fontSize: 13, fontWeight: 600, color: 'var(--div-' + tone + '-accent)' } }, eyebrow) : null, React.createElement('h2', { style: { margin: 0, fontFamily: 'var(--font-display)', fontWeight: 500, fontSize: 44, letterSpacing: '-.025em', lineHeight: .98, textWrap: 'balance' } }, title), intro ? React.createElement('p', { style: { margin: 0, fontSize: 16, lineHeight: 1.55, color: 'var(--text-secondary)' } }, intro) : null,
      React.createElement('div', { role: 'radiogroup', style: { display: 'flex', flexDirection: 'column', gap: 6, paddingTop: 6 } }, options.map((o, i) => { const on = pick === i; return React.createElement('button', { key: i, role: 'radio', 'aria-checked': on, onClick: () => set(i), style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 14, padding: '16px 20px', borderRadius: 16, textAlign: 'left', cursor: 'pointer', fontFamily: 'inherit', transition: 'var(--transition-all)', background: on ? 'var(--action-primary-bg)' : 'rgba(255,255,255,.6)', color: on ? 'var(--action-primary-fg)' : 'var(--text-primary)', border: '1.5px solid ' + (on ? 'var(--border-strong)' : 'transparent') } }, React.createElement('span', { style: { display: 'flex', flexDirection: 'column', gap: 2 } }, React.createElement('span', { style: { fontSize: 16, fontWeight: 600 } }, o.label), o.sub ? React.createElement('span', { style: { fontSize: 13, opacity: .7 } }, o.sub) : null), React.createElement('span', { 'aria-hidden': true, style: { opacity: .6 } }, '›')); }))),
    React.createElement('div', { style: { borderRadius: 24, background: 'var(--surface-raised)', padding: 36, display: 'flex', flexDirection: 'column', gap: 22, minHeight: 420, boxShadow: 'var(--shadow-card)' } },
      r.tags ? React.createElement('div', { style: { display: 'flex', gap: 6, flexWrap: 'wrap' } }, r.tags.map(t => React.createElement('span', { key: t, style: { fontSize: 12, fontWeight: 600, padding: '6px 12px', borderRadius: 999, background: 'var(--div-' + tone + ')' } }, t))) : null,
      React.createElement('span', { style: { fontFamily: 'var(--font-display)', fontSize: 36, fontWeight: 500, letterSpacing: '-.025em', lineHeight: 1, textWrap: 'balance' } }, r.title),
      React.createElement('p', { style: { margin: 0, fontSize: 16, lineHeight: 1.55, color: 'var(--text-secondary)' } }, r.body),
      r.facts ? React.createElement('div', { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, flex: 1 } }, r.facts.map((f, i) => React.createElement('div', { key: i, style: { display: 'flex', flexDirection: 'column', gap: 4, padding: '16px 18px', borderRadius: 16, background: 'var(--surface-card)', border: '1px solid var(--border-default)' } }, React.createElement('span', { style: { fontSize: 12, fontWeight: 600, color: 'var(--text-muted)' } }, f.k), React.createElement('span', { style: { fontSize: 15, fontWeight: 600, lineHeight: 1.35 } }, f.v)))) : null,
      cta ? React.createElement('div', { style: { display: 'flex', gap: 14, alignItems: 'center', paddingTop: 8, borderTop: '1px solid var(--border-default)' } }, typeof cta === 'function' ? cta(r, pick) : cta) : null));
}
